name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test MySQL Container Action
        uses: EyalPazz/mysql-container-action@v0.1.1
        with:
          MYSQL_VERSION: '5.7' # Specify the MySQL version you want to use
          DB_NAME: 'my_database' # Database name
          DB_PASSWORD: 'my_secret_password' # Database password
          DB_PORT: '3306' # Port to expose
